# .github/workflows/crawl.yml
# This workflow automates the process of crawling the Verdragenbank repository.

name: Verdragenbank Crawler

on:
  # Allows manual triggering of the workflow from the Actions tab in GitHub.
  workflow_dispatch:
  # Schedules the workflow to run at 02:00 on every Sunday.
  schedule:
    - cron: '0 2 * * 0'

permissions:
  contents: read

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_REPO: ${{ secrets.HF_DATASET_REPO }}
          HF_PRIVATE: ${{ secrets.HF_PRIVATE }}
        run: |
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            python crawler.py --reset
          else
            python crawler.py
          fi
